### ISSUE TITLE
Sell error on test mode

### ISSUE THREAD

**Issue by jdk-sal3** [cryptobot118/Kucoin-Volatility-Bot#1]
Traceback (most recent call last):
  File "/home/ubuntu/Kucoin-Volatility-Bot/BinanceDetectMoonings.py", line 1426, in <module>
    coins_sold = sell_coins()
  File "/home/ubuntu/Kucoin-Volatility-Bot/BinanceDetectMoonings.py", line 814, in sell_coins
    order_details = client.get_fills(order_id=order_detail_id['orderId'], side='sell')
UnboundLocalError: local variable 'order_detail_id' referenced before assignment

**Comment by phoneywc** [comment]
> Traceback (most recent call last): File "/home/ubuntu/Kucoin-Volatility-Bot/BinanceDetectMoonings.py", line 1426, in coins_sold = sell_coins() File "/home/ubuntu/Kucoin-Volatility-Bot/BinanceDetectMoonings.py", line 814, in sell_coins order_details = client.get_fills(order_id=order_detail_id['orderId'], side='sell') UnboundLocalError: local variable 'order_detail_id' referenced before assignment

Hi jdk-sal3,

Test mode is not really fixed, however the Live mode is working fine for me. Can you perhaps retest with live funds (maybe use low funding as a test) and feedback if this works?
